---

- hosts: WebServers
  become: true
  tasks:

  -  name: install apache2 and php package Ubuntu
     package:
       name: 
       -  apache2
       -  libapache2-mod-php
       state: latest
       update_cache: true
     when: ansible_distribution == "Ubuntu"

  -  name: install apache and php package CentOS
     package:
       name:
       -  httpd
       -  php
       state: latest
       update_cache: true
     when: ansible_distribution == "CentOS"
