- hosts: all
  become: true
  roles: 
    - base

- hosts: WebServers
  become: true
  roles: 
    - WebServers

- hosts: DBServers
  become: true
  roles: 
    - DBServers

- hosts: FileServers
  become: true
  roles:
    - FileServers  
