- name: install apache and php package
  tags: apache,apache2,httpd,php,ubuntu,centos
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start apache service
  tags: apache,apache2,httpd,php,ubuntu,centos
  service:
    name: "{{ apache_service }}"
    state: started  
    enabled: yes

- name: copy html file for site
  tags: apache,apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart_apache
