- name: install apache2 and php package (Ubuntu)
  tags: apache2,php,ubuntu
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start apache2 service (Ubuntu)
  tags: apache2,php,ubuntu
  service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"

- name: install httpd and php package (CentOS)
  tags: httpd,php,centos
  package:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd service (CentOS)
  tags: httpd,php,centos
  service:
    name: httpd
    state: started
  when: ansible_distribution == "CentOS"
