- name: add ssh key for tungnns
      tags: always
      authorized_key:
        user: tungnns
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICkAycsOZQupjYlFBywVlyTsOTFSIsSCIzUshibYZeXw ansible"

