- name: install MariaDB (CentOS)
  tags: mariadb,centos
  dnf:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"
- name: install MariaDB (Ubuntu)
  tags: mariadb,ubuntu
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
